name: Release candidate report
description: Reporting for board maintainers to RC images. **Please put board name into title!**
title: "[RC]: "
labels: ["for review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: board
    attributes:
      label: Board/SBC
      description: On which SBC you are reporting?
      placeholder: ex. Orange Pi Zero, Nanopi R4S, Raxda Zero, ...
    validations:
      required: true
  - type: checkboxes
    id: boot to CLI
    attributes:
      label: Does the board boot to command line interface and does first login procedere including user creation work?

      options:
        - label: macOS
        - label: Windows
        - label: Linux

  
  
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
