name: Release candidate report
description: For each tested image please create individuals ports. Please put image file name into title!
title: "[RC]: "
labels: ["for review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: board
    attributes:
      label: Board/SBC
      description: On which SBC you are reporting?
      placeholder: ex. Orange Pi Zero, Nanopi R4S, Raxda Zero, ...
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: Tested image
      description: Please specify the image you have tested.
      placeholder: ex. Armbian_22.05.1_Clearfogpro_focal_current_5.15.35.img.xz
    validations:
      required: true
      
  - type: checkboxes
    id: boot_to_cli
    attributes:
      label: Does the board boot to command line interface and does first login procedere, including user creation, work?
      options:
        - label: ✔ WORKS 
        - label: ❕ works partially (elaborate below)
        - label: ❌ does not work (elaborate below)
  - type: textarea
      id: what-happened
      attributes:
        label: What happened?
        description: Also tell us, what did you expect to happen?
        placeholder: Tell us what you see!
        value: "A bug happened!"
      validations:
        required: true
