name: Release candidate report
description: Reporting for board maintainers to RC images. **Please put board name into title!**
title: "[RC]: "
labels: ["for review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: board
    attributes:
      label: Board/SBC
      description: On which SBC you are reporting?
      placeholder: ex. Orange Pi Zero, Nanopi R4S, Raxda Zero, ...
    validations:
      required: true
  - type: checkboxes
    id: terms2
    attributes:
      label: Tested functions
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  
  
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
