name: Release candidate report
description: For each tested image please create individuals ports. 
title: "[RC]: "
labels: ["for review"]
body:
  - type: markdown
    attributes:
      value: |
        Please put full image file name into title. ex. Armbian_22.05.1_Clearfogpro_focal_current_5.15.35.img.xz
  - type: checkboxes
    id: boot_to_cli
    attributes:
      label: Does the board boot to CLI and does first login procedere, including user creation, work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: boot_to_gui
    attributes:
      label: Does the board boot to XFCE GUI and is the desktop environment usable normally?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: ssh
    attributes:
      label: Does login to the board via SSH work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: reboot
    attributes:
      label: Does the board reboot?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: lan
    attributes:
      label: If the board has wired networking does it work with expected speed? Do iperf3 test if possible.
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: wireless
    attributes:
      label: If the board has wireless networking does it work? Please do iperf3 test if possible.
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: bt
    attributes:
      label: If the board has bluetooth does it work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: gpio
    attributes:
      label: If the board has GPIO pins do they work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: audio
    attributes:
      label: If the board has analog audio jack does it work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: usb
    attributes:
      label: If the board has USB ports do they work with common devices like memory stick or keyboard?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
        
  - type: textarea
    id: uartboot
    attributes:
      label: UART boot log
      description: If possible provide full boot log from debug serial via UART
      value: |
        <details>
        <pre>
        
        Replace this line with the actual output.
        
        </pre>
        </details>
    validations:
      required: false
  - type: textarea
    id: elaboration
    attributes:
      label: Elaboration
      description: If something does not work properly please try to elaborate further.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false
