name: Release candidate report
description: For each tested image please create individuals ports. 
title: "[RC]: "
labels: ["for review"]
body:
  - type: markdown
    attributes:
      value: |
        Please put image file name into title.
  - type: input
    id: board
    attributes:
      label: Board/SBC
      description: On which SBC you are reporting?
      placeholder: ex. Orange Pi Zero, Nanopi R4S, Raxda Zero, ...
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: Tested image
      description: Please specify the image you have tested.
      placeholder: ex. Armbian_22.05.1_Clearfogpro_focal_current_5.15.35.img.xz
    validations:
      required: true
  - type: checkboxes
    id: boot_to_cli
    attributes:
      label: Does the board boot to CLI and does first login procedere, including user creation, work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: boot_to_gui
    attributes:
      label: Does the board boot to XFCE GUI and is the desktop environment usable normally?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: reboot
    attributes:
      label: Does the board reboot?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: lan
    attributes:
      label: If the board has wired networking does it work with expected speed? Please do iperf3 test if possible.
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: wireless
    attributes:
      label: If the board has wireless networking does it work? Please do iperf3 test if possible.
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: bt
    attributes:
      label: If the board has bluetooth does it work?
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
  - type: checkboxes
    id: hdmi
    attributes:
      label: If the board has wired networking does it work with expected speed? (ex. 100Mbit, 1000Mbit...)
      options:
        - label: ✔ WORKS
        - label: ❌ does not work (elaborate below)
        - label: ➖ untested
        
        
  - type: textarea
    id: uartboot
    attributes:
      label: UART boot log
      description: If possible provide full boot log from debug serial via UART
      value: ""
    validations:
      required: true
  - type: textarea
    id: elaboration
    attributes:
      label: Elaboration
      description: If 
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
